### PR TITLE
Add support for the peripheral derivedFrom attribute.

### PR DESCRIPTION
**Pull request by brandonedens**

### CODE REVIEW

**Comment by japaric** [comment]
(My homu instance is a little bit cranky lately, let's see if this works)

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit aea163a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit aea163a with merge aea163a...

**Comment by japaric** [comment]
*sigh* merging manually (all the tests passed)

@brandonedens Thanks for the PR!

**Pull request merged**
