### PR TITLE
Optional header struct name

### PR DESCRIPTION
**Pull request by brandonedens**
The tag headerStructName is optional. Adjust SVD to account for that.
Bump version of SVD due to incompatible changes surrounding usage of Either<>

### CODE REVIEW

**Comment by japaric** [comment]
Thanks @brandonedens.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4cd4094 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4cd409433345caac2a19ed0704fcb62a9e7034ab with merge da9aa2cc53d41cf25e0c880f120b40431d07593b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/290408357?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing da9aa2cc53d41cf25e0c880f120b40431d07593b to master...

**Pull request merged**
