### PR TITLE
change Peripheral.interrupt's type to Vec<Interrupt>

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9864270 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9864270 with merge 9864270...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/209833738)
Approved by: japaric
Pushing 9864270ad50c3fa587bbf4f63af321f4f5a0a756 to master...

**Pull request merged**
