### PR TITLE
dockerify Travis

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7eaaefb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7eaaefb with merge 7eaaefb...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd/builds/166228644)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a81e40e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a81e40e with merge a81e40e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/166230045)
Approved by: japaric
Pushing a81e40e6d1afa3850479ad106fb4145ffa96dc24 to master...

**Pull request merged**
