### PR TITLE
Recognize <writeConstraint> in <register>

### PR DESCRIPTION
**Pull request by whitequark**

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @whitequark!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5ee1e0a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5ee1e0a with merge 5ee1e0a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/227283880?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 5ee1e0ab9eb0c63a27dee46764dca6dc6db49601 to master...

**Comment by whitequark** [comment]
@japaric A point release, perhaps? I am nearly done with svd2rust and none of the rest of my changes involve the parser.

**Comment by japaric** [comment]
@whitequark v0.5.1 is out.

**Pull request merged**
