### PR TITLE
remove the Invalid WriteConstraint variant

### PR DESCRIPTION
**Pull request by japaric**
and make some structs extensible without breaking backward compatibilty

cc @cwoodall

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1bab96d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1bab96d with merge 1bab96d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/224822791)
Approved by: japaric
Pushing 1bab96d64182ea7b220d0465cbd08abc0007cb15 to master...

**Pull request merged**
