### PR TITLE
fix clippy warnings

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d5d491a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d5d491a with merge d5d491a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/167807783)
Approved by: japaric
Pushing d5d491aa745ee44af53920c151ac590ebe0e59c7 to master...

**Pull request merged**
