### PR TITLE
test on all the channels

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8e61f58 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8e61f58 with merge 8e61f58...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/svd/builds/146902904)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8e61f58 with merge 8e61f58...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit cf0cff9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit cf0cff9 with merge cf0cff9...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/svd/builds/146910128)

**Pull request merged**
