### PR TITLE
add missing variant to Access

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 92ffd62 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 92ffd62 with merge 92ffd62...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/svd/builds/146889617)

**Comment by japaric** [comment]
@homunkulus y no merge?

**Pull request merged**
