### PR TITLE
impl Copy for BitRange

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d480246 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d480246 with merge d480246...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/164655147)
Approved by: japaric
Pushing d480246c0258e054e34f94eb38cb5a01c6ea2ffd to master...

**Pull request merged**
