### PR TITLE
change Field.enumerated_values' type to Vec<EnumeratedValues>

### LINKED ISSUE #19: <field> can have more than one <enumeratedValues> children node
For example, see the [nrf51.svd](https://github.com/posborne/cmsis-svd/blob/master/data/Nordic/nrf51.svd)

``` xml
        <register>
          <name>OUTSET</name>
          ...
            <field>
              <name>PIN0</name>
              <description>Pin 0.</description>
              <lsb>0</lsb> <msb>0</msb>
              <enumeratedValues>  <-
                <usage>read</usage>
                <enumeratedValue>
                  <name>Low</name>
                  <description>Pin driver is low.</description>
                  <value>0</value>
                </enumeratedValue>
                <enumeratedValue>
                  <name>High</name>
                  <description>Pin driver is high.</description>
                  <value>1</value>
                </enumeratedValue>
              </enumeratedValues>
              <enumeratedValues>  <-
                <usage>write</usage>
                <enumeratedValue>
                  <name>Set</name>
                  <description>Set pin driver high.</description>
                  <value>1</value>
                </enumeratedValue>
              </enumeratedValues>
            </field>
```

The `Field` struct will have to be update to reflect this.

### PR DESCRIPTION
**Pull request by japaric**
closes #19

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 261a64f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 261a64f with merge 261a64f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/202864180)
Approved by: japaric
Pushing 261a64f70ac2b40f22bffc6a194c2d8151ba92a8 to master...

**Pull request merged**
