### PR TITLE
CI: use the trust template

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ccac11e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ccac11e with merge ccac11e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/190020024)
Approved by: japaric
Pushing ccac11ea3c7181f3c073acfe55efff8da8c6b1f4 to master...

**Pull request merged**
