### PR TITLE
add utility `parse` function, remove the `parse` binary

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0f5321f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0f5321f with merge 0f5321f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd/builds/166224460)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0a04989 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0a04989 with merge 0a04989...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/166225129)
Approved by: japaric
Pushing 0a0498978441c49c1fdf5defb2a8dc078b4a5ab7 to master...

**Pull request merged**
