### PR TITLE
Switch BitRange parsing to parse::u32 so hex-format values work

### PR DESCRIPTION
**Pull request by pinealservo**
This is a fix for #31; it allows my MSP432 SVD file to parse correctly.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks @pinealservo!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0989dbc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0989dbc with merge 0989dbc...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/236181422?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 0989dbcb6c0924a6a1f34969f8d9550c443e682d to master...

**Pull request merged**
