### PR TITLE
Add --all-features to ci build and test

### PR DESCRIPTION
**Pull request by ryankurte**
CI is not currently running tests as they're feature gated

### CODE REVIEW

**Comment by ryankurte** [comment]
bors try

**Comment by japaric** [comment]
@ryankurte I forgot to sync the collaborators list on bors; you should be able to bors try now.

bors try

**Comment by ryankurte** [comment]
Woo, thanks!

bors try

**Comment by japaric** [comment]
@ryankurte, sorry. I forgot about this.

bors r+

**Pull request merged**
