### PR TITLE
.travis: remove webhooks

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 58744d1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 58744d1 with merge 58744d1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/174111508)
Approved by: japaric
Pushing 58744d100e088bae9ad7d2e84adfd6e02f8481cd to master...

**Pull request merged**
