### PR TITLE
suppor for register arrays

### PR DESCRIPTION
**Pull request by japaric**
cc @istankovic

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8a99ce0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8a99ce0 with merge 8a99ce0...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/185641500)
Approved by: japaric
Pushing 8a99ce0dafed9446ea4d9288360e26428ada6d61 to master...

**Pull request merged**
