### PR TITLE
Feature/svd clusters

### PR DESCRIPTION
**Pull request by brandonedens**
Add parsing of the <cluster> tag along with the creation of Cluster and ClusterInfo where ClusterInfo represents the children tags that are applicable to <cluster>.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @brandonedens.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit cd5aefa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit cd5aefa with merge cd5aefa...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd/builds/278252401?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing cd5aefacb0f439fca1e8e5bf8cad3008439286c3 to master...

**Pull request merged**
